apiVersion: vspherevirtualmachine.vsphere.jet.crossplane.io/v1alpha1
kind: Machine
metadata:
  name: hello-crossplane-vm
spec:
  forProvider:
    resourcePoolId: "myResourcePoolId"
    datastoreId: "myDatastoreId"
    numCpus: 2
    memory: 1024
    guestId: "other3xLinux64Guest"
    networkInterface:
    - networkId: data.vsphere_network.network.id
    disk:
    - label: "disk0"
      size: 20
  providerConfigRef:
    name: default